name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-pre*'

jobs:
  release-pypi:
    name: Release package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies for building
        run: |
          python3 -m pip install -U pip wheel setuptools
          python3 -m pip install -U twine build
      - name: Build Repository
        run: python3 -m build --sdist --wheel --outdir dist/
      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
  release-docker:
      name: Release package to Docker
      runs-on: ubuntu-latest
      needs: release-pypi
      if: "! contains(github.ref, 'pre')"
      steps:
        - name: Repository Checkout
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build Docker Image # image/Dockerfile
          uses: docker/build-push-action@v2
          with:
            context: .
            file: image/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/SNL2023f:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/SNL2023f:${{ github.ref }}


          